version: '2'
services:
  iloveu:
    ports:
      - 9999:80
    build:
      context: ./
    container_name: iloveu
    hostname: iloveu
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai